dist: bionic
addons:
  apt:
    packages:
      - libfuse-dev

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - name: fmt
      rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
  allow_failures:
    - rust: nightly
  fast_finish: true
