name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build-ubuntu-fuse2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install libfuse-dev
        run: sudo apt-get install -y libfuse-dev

      - name: Build
        run: cargo build --features fuse_26 --verbose

  build-ubuntu-fuse3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install libfuse3-dev
        run: sudo apt-get install -y libfuse3-dev

      - name: Build
        run: cargo build --features fuse_35 --verbose


  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install macfuse
        run: brew install macfuse

      - name: Build
        run: cargo build --verbose

      - name: Upload bindings
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: fuse_bindings
          path: |
            target/fuse.rs
            target/fuse_lowlevel.rs
